### ISSUE TITLE
多服务支持

### ISSUE THREAD

**Issue by scavin** [pandolia/easy-service#1]
请问如何实现多个服务注册的支持，需要运行多个 svc 么？配置文件中未找到多服务设置方法。

**Comment by pandolia** [comment]
是的，需要运行多个 svc 。把 svc.exe 和 svc.conf 放在不同的目录下面就可以了，注意服务名不要冲突。

如果确实需要一个 svc 服务中启动多个 Worker 子进程，可以考虑修改源码 src/main.cs 。
