### ISSUE TITLE
Directory argument "service-name" should contain '/' or '\'

### ISSUE THREAD

**Issue by liesauer** [pandolia/easy-service#11]
这也太不人性化了吧，这在程序中能轻而易举实现的判断和字符串拼接，却让用户去做。

**Comment by liesauer** [comment]
完全想不明白

**Comment by pandolia** [comment]
强制要求目录参数加斜杠，是为了和服务名区别开来。svc 命令的第二个参数，可以是 目录、服务名、服务序号 或者 all ，按以下原则进行区分：

1. 如果第二个参数为 all ，则对所有服务进行操作。比如，输入 svc start all ，则启动所有服务。

2. 如果第二个参数是数字，则对第 i 个服务进行操作。比如，输入 svc start 1 ，则启动第 1 个服务。

3. 如果第二个参数中不含斜杠或反斜杠，则对名称为该参数的服务进行操作。比如，输入 svc start hello-svc ，则启动名称为 hello-svc 的服务。

4. 如果第二个参数中含有斜杠或反斜杠，则对目录为该参数的服务进行操作。比如，输入 svc start aa\ ，则启动 aa\svc.conf 配置文件中指定的服务。

对于上述第 3 和第 4 种情况，有两种方案进行区分：

1. 方案一，用命令行参数进行区分，比如 svc start --name hello-svc 和 svc start --directory aa 。

2. 方案二，强制规定参数中含斜杠或反斜杠就是第 4 中情况，比如 svc start hello-svc 和 svc start aa\ 。

方案一、二各有优缺点吧。从少打几个字符的方面考虑，本软件最终选择的是方案二。

**Comment by liesauer** [comment]
不需要使用`--name`和`--directory`长参数这么麻烦，默认下按3的情况处理，即名字，使用短参数`-d`参数来指定目录服务即可，从一个常规的命令行程序来讲，这样子绝对很nice的，包括不需要特殊的`/`和`\`做奇怪的判断，用户友好度也提升不少。

**Comment by pandolia** [comment]
加短参数和强制使用斜杠，没什么区别吧。而且对于目录来说，一般也是要加斜杠的（用来和文件区分开来）。

**Comment by liesauer** [comment]
长度上是没什么区别，但是用户体验上就有区别了，第一次使用肯定会给人一种莫名其妙的感觉。
