### ISSUE TITLE
win10 家庭版也出现重启后无法自启动

### ISSUE THREAD

**Issue by snailg** [pandolia/easy-service#12]
win10 家庭版也出现重启后无法自启动，前提已经注册为服务。

**Comment by pandolia** [comment]
能看一下日志吗？svc.log 还有 svc.exe 同目录下的日志。

**Comment by pandolia** [comment]
@snailg 兄弟，您说的问题现在没有了吗？

**Comment by snailg** [comment]
> @snailg 兄弟，您说的问题现在没有了吗？

没有了。不知道为什么第一次重启不行，后面在关机或者重启都正常了。

**Comment by snailg** [comment]
![image](https://user-images.githubusercontent.com/5671609/114116021-808d3480-9916-11eb-9890-bcf385c17bdb.png)
![image](https://user-images.githubusercontent.com/5671609/114116085-93a00480-9916-11eb-8803-dcf8c8776f45.png)
昨天晚上关机后，今天早晨打开还是不行了，这是截图信息，请大佬指教。

**Comment by snailg** [comment]
用svc list查看服务状态是stopped，我必须得用手动启动一下才会变成running。
![image](https://user-images.githubusercontent.com/5671609/114116289-fbeee600-9916-11eb-9e76-7d80687983f0.png)

**Comment by pandolia** [comment]
麻烦发一下您的程序和配置文件吧，我测试一下，谢谢。

**Comment by snailg** [comment]
2021/04/09 09:23:15 [W] [control.go:288] [fa2e48f6859c8373] heartbeat timeout
2021/04/09 09:23:16 [E] [control.go:147] [fa2e48f6859c8373] work connection closed before response StartWorkConn message: EOF
2021/04/09 09:23:16 [I] [control.go:251] [fa2e48f6859c8373] control writer is closing
2021/04/09 09:23:16 [I] [service.go:148] [fa2e48f6859c8373] try to reconnect to server...
2021/04/09 09:23:16 [W] [service.go:151] [fa2e48f6859c8373] reconnect to server error: dial tcp 121.41.63.124:1556: connectex: A socket operation was attempted to an unreachable network.
2021/04/09 09:23:17 [I] [service.go:148] [fa2e48f6859c8373] try to reconnect to server...
2021/04/09 09:23:18 [I] [service.go:249] [fa2e48f6859c8373] login to server success, get run id [fa2e48f6859c8373], server udp port [0]
2021/04/09 09:23:18 [I] [proxy_manager.go:144] [fa2e48f6859c8373] proxy added: [lv-desktop]
2021/04/09 09:23:18 [I] [control.go:164] [fa2e48f6859c8373] [lv-desktop] start proxy success
Exception 0xc0000006 0x0 0xa4341c 0x4471c3
PC=0x4471c3

2021/04/09 09:35:30 [I] [service.go:249] [770a78a5ce0a03b2] login to server success, get run id [770a78a5ce0a03b2], server udp port [0]
2021/04/09 09:35:30 [I] [proxy_manager.go:144] [770a78a5ce0a03b2] proxy added: [lv-desktop]
2021/04/09 09:35:30 [I] [control.go:164] [770a78a5ce0a03b2] [lv-desktop] start proxy success



麻烦您给分析下这个启动日志，是不是由于我调用的程序本身有问题才导致服务没有正常启动的。感谢。

**Comment by pandolia** [comment]
这一行好像是抛了一个错误
2021/04/09 09:23:18 [I] [control.go:164] [fa2e48f6859c8373] [lv-desktop] start proxy success
Exception 0xc0000006 0x0 0xa4341c 0x4471c3
PC=0x4471c3

**Comment by snailg** [comment]
是不是因为这个错误导致服务没有正常启动，win10 家庭版没有开启3389远程端口的功能，我是找的工具强开的，估计会有bug....

**Comment by pandolia** [comment]
你试试把管理员用户和密码加到配置文件里面去，install 之后（第一次运行可能会失败），到 控制面板 -> 管理工具 -> 服务 里面，找到那个服务，双击，点 登录 ，点一下 此账户 ，再点应用或授权此账户运行服务的权限。
![图片](https://user-images.githubusercontent.com/13767061/114118235-0ca15b00-991b-11eb-9e6c-c43844f6220f.png)

![图片](https://user-images.githubusercontent.com/13767061/114118807-0a8bcc00-991c-11eb-9662-6d0944b6dd0c.png)

**Comment by snailg** [comment]
好的  我试一下。请问Domain填什么内容？

**Comment by pandolia** [comment]
空着就行

**Comment by snailg** [comment]
按照您说的照着设置了依然不行，我估计是我的系统问题，我看服务的启动类型是自动，但是没有自动启动，我的redis服务也是这种情况。

**Comment by pandolia** [comment]
方便的话可以加我的 QQ 158297369 ，帮你远程看一下。

**Comment by snailg** [comment]
感谢大佬的耐心指导。

**Comment by pandolia** [comment]
不客气。
我发现Win10 下面 Domain 不能留空，需要用 “.”
