### ISSUE TITLE
arthas

### ISSUE THREAD

**Issue by zks939674644** [pandolia/easy-service#14]
if we use easy-service,the arthas can not find java process.

**Comment by pandolia** [comment]
不好意思，现在才看到这个 issue 。

因为 easy-service 默认情况下会使用 LOCAL-SYSTEM 用户运行 worker 进程，所以你的 java 进程会在 LOCAL-SYSTEM 用户下运行，如果你以普通用户运行 arthas ，那就会找不到 java 进程。解决方法：
1. 以 LOCAL-SYSTEM 用户运行 arthas （这个我也不知道怎么操作）；
2. 在 svc.conf 配置文件中，指定 Domain 、User 、 Password 三个选项，让 easy-service 使用普通用户运行 worker 进程。（这个方法我试过了，可以找到 java 进程）。

关于第二个方法，使用普通用户运行 worker 进程，需要注意： 1. 如果 Domain 不确定，请设置为 “.” （点号）；2. 注册服务后，如果服务启动失败，需要在 计算机管理-服务 中找到你的服务，双击，点登录，再点此账户，输入用户名和密码，再启动服务，见下图。

![图片](https://user-images.githubusercontent.com/13767061/149703682-f08fdd94-f4fe-49da-b98f-9fbb6084fa09.png)

**Comment by pandolia** [comment]
I'm sorry, I didn't see this issue until today.

Easy-Service will run the worker process under user `LOCAL-SYSTEM` by default. If you run arthas under nomal user, you `can not` find your worker process.

Solution 1: Run arthas under user LOCAL-SYSTEM.

Solution 2: Set configurations "Domain,User,Password" in svc.conf. Let Easy-Service run the worker process under normal user. I have tried this method, it works, the arthas can find the worker process.

For solution 2, first: If you are uncertain about "Domain", just set it to ".". Second, after you install your service, if it fails to start, you need to open "system service panel", and grant the autority of run service to the user who you want to run the service.
![149703682-f08fdd94-f4fe-49da-b98f-9fbb6084fa09](https://user-images.githubusercontent.com/13767061/149705866-947b3e59-9a2c-4c69-8cf5-81a1f757c42d.png)

**Comment by pandolia** [comment]
另外，提 ISSUE 的话最好在标题里把问题描述一下。
