### ISSUE TITLE
拒绝访问

### ISSUE THREAD

**Issue by naruco** [pandolia/easy-service#2]
执行check和test-worker都OK
但install时一直提示拒绝访问，会是什么原因？

**Comment by pandolia** [comment]
是用管理员账号吗？配置文件中 Domain/User/Password 三个都需要设置为空。

**Comment by pandolia** [comment]
Win10 系统下，需要：在开始菜单中搜索 cmd 然后右键以管理员身份运行，再 cd 到 svc.conf 所在的目录下运行 **.\\svc install** 。
