### ISSUE TITLE
Failed to create Worker

### ISSUE THREAD

**Issue by Virace** [pandolia/easy-service#6]
`[ERROR] Failed to create Worker `python main.py` in `***\worker`
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 Program.startWorker()`

默认脚本

**Comment by pandolia** [comment]
svc test-worker 命令可以运行吗？

**Comment by Virace** [comment]
都是正常的 这个日志是安装服务之后运行 才出现的

**Comment by pandolia** [comment]
应该找不到 python 命令而引起的。试试改为 python.exe 的绝对路径，或者安装 python 的时候设置为所有用户可用。

**Comment by Virace** [comment]
绝对路径怎么添加 加上路径 Worker会提示 有特殊字符

**Comment by pandolia** [comment]
汗，上次 @lizenghuan 增加 checkValid 函数把冒号加进来了。。。稍等一下，我改一下重新编译一个文件。

**Comment by Virace** [comment]
好的

**Comment by pandolia** [comment]
好了，现在可以设置绝对路径了。

**Comment by pandolia** [comment]
你下载新的文件再试一下吧。

**Comment by pandolia** [comment]
如果绝对路径中有空格，要用双引号括起来

**Comment by Virace** [comment]
ok
