### ISSUE TITLE
功能问题

### ISSUE THREAD

**Issue by tinyhugh** [pandolia/easy-service#7]
我在使用svc.exe test-worker 命令后，我的程序可以正常运行，但是在使用install命令安装服务后再打开却不能正常运行。
而且使用svc.exe test-worker 命令运行后在任务管理器里面找不到我的程序进程，但当我去尝试删除我的程序时，系统提示文件已经被打开。
这个程序
https://public01-1251017876.cos.ap-beijing-1.myqcloud.com/%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%8E%A7%E5%88%B6%E9%9F%B3%E9%87%8F.zip
程序界面是不可见，功能是按下Ctrl Shift Win Num+来控制系统音量增加，Ctrl Shift Win Num-来控制系统音量减小。

**Comment by pandolia** [comment]
易语言编的？我这边下下来就被杀毒软件删除了。
可能你调用的某些 Windows GUI 相关的 API 无法以 Service 模式运行，一般情况下，程序最好是 Console 模式的可执行文件。
另外，可以把这个文件放到启动目录下，Win7 下，点 开始 -> 所有程序 -> 启动 ，可以找到这个目录，也就是： C:\Users\？？？\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup ，这个程序会在你登录进入桌面后开始运行。

**Comment by tinyhugh** [comment]
是易语言编写的，用到了sendmessage api，这个好像需要窗口对象才可以实现，而服务程序不允许创建窗口，可是有些不理解的是为什么用svc.exe test-worker 命令后可以正常运行？

**Comment by pandolia** [comment]
test-worker 命令是将程序在当前用户、当前窗口下运行的，所以并没有以服务程序运行。
